name: Server Docker Image CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Get timestamp
              id: vars
              run: echo "ts=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

            # Build & Push Server image
            - name: Build & Push Server Docker Image
              uses: docker/build-push-action@v6
              with:
                  context: ./server
                  push: true
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/gradient-descent-visualiser-server:latest
                      ${{ secrets.DOCKERHUB_USERNAME }}/gradient-descent-visualiser-server:${{ steps.vars.outputs.ts }}

            - name: Deploy Server Render Web Service
              env:
                  deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
              run: |
                  curl "$deploy_url"
